export const SKILL_MAP = {
  'After Effects': 'AFTER_EFFECTS',
  AWS: 'AWS',
  'C#': 'CSHARP',
  CRM: 'CRM',
  Django: 'DJANGO',
  'express.js': 'EXPRESS',
  FastAPI: 'FAST_API',
  Figma: 'FIGMA',
  GA4: 'GA4',
  Illustrator: 'ILLUSTRATOR',
  Java: 'JAVA',
  Javascript: 'JAVASCRIPT',
  Jira: 'JIRA',
  Kotlin: 'KOTLIN',
  NestJS: 'NEST_JS',
  'Next.js': 'NEXT_JS',
  'Node.js': 'NODE_JS',
  'MongoDB': 'MONGODB',
  Notion: 'NOTION',
  Photoshop: 'PHOTOSHOP',
  ProtoPie: 'PROTO_PIE',
  Python: 'PYTHON',
  React: 'REACT',
  'React Native': 'REACT_NATIVE',
  SEO: 'SEO',
  SNS마케팅: 'SNS_MARKETING',
  Spring: 'SPRING',
  SQL: 'SQL',
  TypeScript: 'TYPESCRIPT',
  UE: 'UE',
  Unity: 'UNITY',
  'Vue.js': 'VUE',
  콘텐츠제작: 'CONTENT_CREATION',
} as const;
